FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

# libssl-dev:armhf && \

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes \
    openssl:armhf \
    libssl-dev:armhf \
    && rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
